### ISSUE TITLE
Error: Unknown command

### ISSUE THREAD

**Issue by as280093** [ezhevita/GameRemover#58]
```
2022-07-19 22:49:32|ArchiSteamFarm-15556|ERROR|ASF|OnBotCommand() System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'steamID')
   at ArchiSteamFarm.Core.ASF.IsOwner(UInt64 steamID)
   at GameRemover.GameRemoverPlugin.ResponseDeleteGame(UInt64 steamID, EAccess access, String botNames, String appIDText)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
2022-07-19 22:50:17|ArchiSteamFarm-15556|ERROR|ASF|OnBotCommand() System.IO.FileNotFoundException:
File name: 'AngleSharp, Version=0.16.1.0, Culture=neutral, PublicKeyToken=##############'
   at GameRemover.GameRemoverPlugin.ResponseDeleteGame(Bot bot, EAccess access, String appIDText)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& )
   at GameRemover.GameRemoverPlugin.ResponseDeleteGame(Bot bot, EAccess access, String appIDText)
   at GameRemover.GameRemoverPlugin.<>c__DisplayClass7_0.<ResponseDeleteGame>b__1(Bot bot)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at GameRemover.GameRemoverPlugin.ResponseDeleteGame(UInt64 steamID, EAccess access, String botNames, String appIDText)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
```
command used `deletegame 580495` & `deletegame bot1 580495`

**Comment by ezhevita** [comment]
Hello, thanks, I'll try to fix this in the next update!

**Comment by ezhevita** [comment]
Hi, this should be fixed. Please test and if it still doesn't work - reopen the issue. Have a good day!
